### ISSUE TITLE
Rule evaluation caching

### ISSUE THREAD

**Issue by markphelps** [markphelps/flipt#100]
**Describe the solution you'd like**

Would like to support evaluation caching for rule based evaluation. IE https://flipt.dev/concepts/#evaluation

This would behave similarly to what was added in #6, but would likely be more complex since there are multiple entities that need to be cached (segments, distributions, rules, variants, etc) and invalidated.

One approach is to just cache the evaluation result and not the actual individual actors (noted above), but would have to come up with a scheme to invalidate this cached result if any of the above changed.

**Comment by badboyd** [comment]
Can we open it again?

**Comment by badboyd** [comment]
Can we just cache the rules and distributions, and do the evalutaion? Then let the cache be purged after an expiration time.

**Comment by markphelps** [comment]
Yep! Ive actually started working on this this week

**Comment by markphelps** [comment]
Tracking in https://github.com/markphelps/flipt/tree/cache-redo, I hope to have this land early this coming week

**Comment by markphelps** [comment]
@badboyd this should be fixed as of [v0.12](https://github.com/markphelps/flipt/releases/tag/v0.12.0)

The docs on the caching feature are here: https://flipt.io/docs/configuration/#caching

Lemme know how it works for you!
