### ISSUE TITLE
Auto populate `key` fields based on `name`

### ISSUE THREAD

**Issue by markphelps** [markphelps/flipt#136]
## Problem

When creating a new flag/segment/etc, you have to type the `name` and `key` field before saving as they are both required.

## Purposed Solution

It would be nice if the `key` field autopopulated based on the `name` fields as they are often closely related.

### Example

![Screen Shot 2019-09-22 at 11 03 33 AM](https://user-images.githubusercontent.com/209477/65389960-e01df200-dd28-11e9-9991-1a5bdb97178c.png)

**^ In the above screenshot, it would be nice if `key` was autopopulated to `foo-bar`**

Also consider if it makes sense to swap the position of the `name` and `key` fields in the form

**Comment by aaronraff** [comment]
I can look into this over the weekend if you haven't already started on it. I'm not sure if there is anything else to jump in on since all the issues are currently assigned to you.

**Comment by markphelps** [comment]
That would be great, thanks @aaronraff!  I went ahead and unassigned myself from the others too because I haven't started on any of them, just incase you'd prefer one of the other issues.

**Comment by aaronraff** [comment]
@markphelps I'll take a look at this one first. Thanks!
