### ISSUE TITLE
Handle unmarshalling errors better

### ISSUE THREAD

**Issue by markphelps** [markphelps/flipt#137]
It would be great if we could handle unmarshalling errors more gracefully during evaluation.

## Example

![Screen Shot 2019-09-22 at 11 08 31 AM](https://user-images.githubusercontent.com/209477/65390034-82d67080-dd29-11e9-8706-7decd580505b.png)

## Ideas

1. Catch unmarshalling errors and return a nicer error that informs the user that values must be strings
1. Infer `"true"` from `true` and 'autobox' the type into a string

**Comment by markphelps** [comment]
This is handled by grpc-gateway, so we should implement our own error handler per: https://mycodesmells.com/post/grpc-gateway-error-handler

https://grpc-ecosystem.github.io/grpc-gateway/docs/customizingyourgateway.html

**Comment by aaronraff** [comment]
I can take a a look into this one. I'm leaning towards starting with idea 1, if that sounds like a good plan to you.

**Comment by aaronraff** [comment]
I started taking a look into this over the weekend. I took a look at the blog post that you linked in this issue. After implementing that, this is the error that is made available to us through the custom handler: `rpc error: code = InvalidArgument desc = json: cannot unmarshal bool into Go value of type string`.

It seems like we would probably need to add some custom logic when decoding the json (https://golang.org/pkg/encoding/json/#Decoder). Is this desired, or did you have a simpler solution in mind for this? Maybe I am missing something here.

**Comment by markphelps** [comment]
Thanks for taking a look @aaronraff!

My initial thoughts were to be able to return something like `context values must be strings` or something similar if we failed to unmarshal those values, however after thinking about it some more, it may not be worth the trouble at the moment to implement a custom decoder just to do that.

What do you think?

**Comment by aaronraff** [comment]
I don't mind trying it out, but if there are other issues that you feel are more important, I can jump on one of those.

Sounds like a cool idea for a library though!

**Comment by markphelps** [comment]
I think im gonna close this since it's not really critical. There's another issue that I could use your help on re the automatic 'slugifying' of flag/segment keys from the name that was added in #155. I'll create an issue for that
