### ISSUE TITLE
Turn feature flags on/off based on segment

### ISSUE THREAD

**Issue by noasic** [markphelps/flipt#138]
I could use an easy way to turn feature flags on and off based on segments.

As an example, my web application has a feature called "projects" that I would like to enable only for users that have subscribed to the "professional" plan. As far as I know, the only way to do that in  flipt is to create two variants of the flag ("enabled" and "disabled"), and to map those variants to segments corresponding to the plans ("basic" or "professional").

Having to create those variants is a bit inconvenient as all I really want to do is just switch the flag on or off.

**Comment by markphelps** [comment]
@noasic please checkout #145 and let me know if that will fit your workflow

Thanks!
