### ISSUE TITLE
Support logging to file

### ISSUE THREAD

**Issue by markphelps** [markphelps/flipt#141]
**Is your feature request related to a problem? Please describe.**
Currently logs only go to STDOUT, would be great to support logging to the filesystem

**Describe the solution you'd like**
Support logging to file in configs

**Comment by aaronraff** [comment]
I am very new to this project but if you are looking for someone to lend a hand on either this issue or some other one, I would be happy to help out.

**Comment by markphelps** [comment]
Awesome. That would be great @aaronraff !

I was thinking it could be implemented somewhat like this: https://github.com/sirupsen/logrus/issues/156#issuecomment-457577130

With adding a field to the config: https://github.com/markphelps/flipt/blob/3430f47942167ce16a1e0fc6dd6272bd835584e4/config/local.yml#L1

Something like:

```yaml
log:
  level:
  file: filename.log
```

I guess if file was empty or didn't exist it would just log to STDOUT like it currently does

**Comment by markphelps** [comment]
@all-contributors please add @aaronraff for code
