### ISSUE TITLE
Error: Total percentage cannot exceed 100%.

### ISSUE THREAD

**Issue by 4n70w4** [markphelps/flipt#186]
I add 280 variants to one flag.
I go to `Targeting` tab and click `New Rule`.
I select `A Percentage Rollout`.
Interface draw my 280 variants with fre-filled 0,36%
I click `Add Rule` and get error `Total percentage cannot exceed 100%.`

Because 280 * 0,36 = 100,8

Flipt incorrectly calculated the initial values.

**Comment by markphelps** [comment]
Thanks for the bug report @4n70w4 

This will be fixed in the next release (v0.10.5) as it's fixed on master
