### ISSUE TITLE
Increase test coverage to > 80%

### ISSUE THREAD

**Issue by markphelps** [markphelps/flipt#2]
Increase aggregate test coverage to > 80%

**Comment by u5surf** [comment]
@markphelps 
I would like to try this issue.
At fast, coverage is lesser than 70% would be increased.

wip: 
server/flag_test.go 
server/rule_test.go
server/flag_test.go

**Comment by markphelps** [comment]
Awesome! I appreciate the help @u5surf !

**Comment by markphelps** [comment]
Hey @u5surf , I noticed your build seems to be failing on Travis because of the import paths not matching the expected: `github.com/markphelps/flipt`. I think it's because you forked the repo and cloned to your own path.

You may want to checkout https://medium.com/@sasom/how-to-fork-go-packages-f863e370bbb6 

Hope that helps!

**Comment by u5surf** [comment]
@markphelps 
I added https://docs.travis-ci.com/user/languages/go/#go-import-path, then travis build was done.

**Comment by markphelps** [comment]
Awesome, feel free to submit a PR and I can help with any merge conflicts. Sorry I renamed some things :(
