### ISSUE TITLE
Add e2e UI tests

### ISSUE THREAD

**Issue by markphelps** [markphelps/flipt#216]
**Is your feature request related to a problem? Please describe.**
Add some end to end UI tests to verify that changes do not break the Flipt UI and that users see the expected results.

**Describe the solution you'd like**
Perhaps something like [testcafe](https://devexpress.github.io/testcafe/)? I dont know much about the 'modern' e2e Javascript testing frameworks.. but I know things I DO NOT WANT:

❌ **No** ❌ :
* Selenium or browser based tests as these are slow and error prone
* BDD testing language, just want simple easy to write expectation based tests

**Additional context**
Something that could capture screenshots when tests fail would be nice too for local development

**Comment by jperl** [comment]
👋 Hello I maintain an [open source library](https://github.com/qawolf/qawolf) that generates [Playwright](https://github.com/microsoft/playwright) code. I would be happy to submit PRs setting up e2e tests, if you are cool with them using Playwright?

**Comment by markphelps** [comment]
@jperl Yes that would be awesome! This is the first I've heard of Playwright, but it looks great, as does QAWolf (love your landing page btw).

**Comment by jperl** [comment]
Awesome, I will start working on a PR next week!
