### ISSUE TITLE
Using DB to keep track of migrations

### ISSUE THREAD

**Issue by kceb** [markphelps/flipt#223]
**Is your feature request related to a problem? Please describe.**

I'm currently using unleash, but I'm considering flipt. I'm going through the docs and noticed that migrations are kept in the `db.migrations.path` config, which points to a local file. There is no indication that migrations are stored locally, but I'd love to be wrong. 

Edit: Are these files similar to migration files in rails or are they used to keep track of what migrations have been run? If the former, then I assume the DB _does_ keep track of migrations.

**Describe the solution you'd like**

A way to store all data in a db, so that I don't need to configure permanent storage for my ECS/Fargate setup.

**Additional context**
N/A

**Comment by markphelps** [comment]
Hey @kceb 

You are correct in that the migration files are used similarly as they are in Rails. In particular, Flipt uses [go-migrate](https://github.com/golang-migrate/migrate) to handle migrations.

It keeps track of which migrations have been run by [storing the current migration version number in the database](https://github.com/golang-migrate/migrate/blob/master/FAQ.md#do-i-need-to-create-a-table-for-tracking-migration-version-used)

Currently, Flipt will migrate the database (if required) by running `flipt migrate` from the command line. If you update to a new version of Flipt that contains new database migrations, Flipt will detect that migrations need to be run and ask you to run `flipt migrate`.

More detail here: https://flipt.io/docs/configuration/#migrations

Hope that helps!
