### ISSUE TITLE
Multi-tenancy database support

### ISSUE THREAD

**Issue by geoom** [markphelps/flipt#232]
I have multiple databases (aka tenant) since I developed a multi-tenancy system, every tenant is a customer who owns a site https://[tenant_name].mysystem.com, how can I smoothly toggle features for a specific tenant using Flipt?

**Comment by badboyd** [comment]
+1 for this request

**Comment by markphelps** [comment]
@geoom interesting use case. Originally Flipt was not meant to support the use case of a single Flipt instance covering multiple applications. It seems your use-case is more for different virtual hosts?

The original idea was that you could use Flipt to on a multi-tenant system like how GitHub is multi-tenant (same application code but each user has their own data).

Just to confirm, are each of your tenants running the same application code? Or is there different code that can run on each site?

**Comment by geoom** [comment]
@markphelps all tenants only share same application code but each one has its own database.

what do you mean "original idea was" ? imho that's a killer feature and a big advantage compared to Unleash.

**Comment by markphelps** [comment]
Ohh I think I didn't read it correctly in the first place. So each customer actually has it's own physical database? Got it.

How would you want this feature to work? 

Currently, you can create different [segments](https://flipt.io/docs/concepts/#segments) for your customers, and then define [rules](https://flipt.io/docs/concepts/#rules) based on those segments.

This would allow you to toggle features on/off for specific customers based on the evaluation.

Maybe I'm not understanding what you want to do fully?

**Comment by geoom** [comment]
I am not sure, *segments* sounds like a tag for a bunch a tenants, so I wont be able to toggle features for specific customers but for specific bunch of customers as segments. 

It's seems a workaround but it doesn't add a really support to multiple databases like as I explained in my original request. Anyway, Flipt looks promising, I'll going to try out some of its features.

**Comment by markphelps** [comment]
Im still not 100% sure on what the solution is you are looking for. Flipt doesnt access your data/databases. It only maintains its own database to store flags/segments/etc.

It's up to the logic in your application to integrate Flipt into how your data is modeled. Going to close this for now, if Flags or Segment's still don't work for your use case. Please open a new issue with this template: https://github.com/markphelps/flipt/issues/new?assignees=markphelps&labels=enhancement&template=feature_request.md&title=

Any usescases, mockups or drawings or anything may help me better understand what this feature would look like.
