### ISSUE TITLE
Evaluating all flags

### ISSUE THREAD

**Issue by ardyfeb** [markphelps/flipt#257]
**Is your feature request related to a problem? Please describe.**
Feature, allow evaluate all available flags

**Describe the solution you'd like**
Querying available flags which is return all flags that fit for current context. Example:
```http
GET /api/v1/evaluate_all
{
  "entity_id": "string",
  "context": {
    "property1": "string",
    "property2": "string"
  }
}
```
and returns

```json
{
  "entity_id": "string",
  "request_context": {
    "property1": "string",
    "property2": "string"
  },
  "match_flags": [
      {
        "key": "string",
       "value": "string"
      }
  ]
}
```

**Additional context**

**Comment by markphelps** [comment]
@ardyfeb evaluating all flags would not be very performant as it would have to loop through each and determine which segments/constraints they match.

Would something like #61 help instead?
