### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by dcramer** [markphelps/flipt#259]
https://github.com/getsentry/flipt-grpc-python

just an fyi in case you wanna document it. can add you to the repo.

also added a Makefile which may be useful in other repos?

we're exploring using flipt so this is needed for our eval

**Comment by markphelps** [comment]
@dcramer Amazing thank you! Will add to the README. I'd be honored if Sentry used Flipt, big fan of Sentry as we use it at GitHub. Lmk how it goes and if theres any questions I can answer!
