### ISSUE TITLE
Flags with special characters

### ISSUE THREAD

**Issue by dcramer** [markphelps/flipt#262]
**Describe the bug**
Adding a flag with a `:` character breaks the UI. e.g. ``foo:bar``

**Comment by markphelps** [comment]
Thanks for reporting @dcramer. I'll work on this ASAP

**Comment by markphelps** [comment]
Confirmed. GRPC Gateway issue here that I believe is causing this: https://github.com/grpc-ecosystem/grpc-gateway/issues/224

**Comment by markphelps** [comment]
Not stale, currently working on it
