### ISSUE TITLE
flipt import read from STDIN

### ISSUE THREAD

**Issue by giddel** [markphelps/flipt#278]
For backup the sqlite database I can use `flipt export` which pipes to STDOUT. In our k8s environment this looks so:
`kubectl exec -it <name of flipt pod> -- /bin/sh -c './flipt export' > export.yaml `
... and works like a charm :-)

But now I wonder how to import the the backup since `flipt import` wants to read from a file, not from STDIN. I've tried a lot of variants, all ended in `Error: requires a file argument` :-(

So it would be great, if I can do a `flipt import` to read from STDIN for restoring backups in a docker or k8s environment.

**Comment by giddel** [comment]
Little update of my idea:
Why not provide API endpoints for export and import the data?
And once we have API endpoints, why not provide these maintenance feature from the admins frontend?

**Comment by markphelps** [comment]
@giddel I just released https://github.com/markphelps/flipt/releases/tag/v0.14.0 which should allow you to import from STDIN. I also updated the docs here: https://flipt.io/docs/configuration/#import

Thanks for the feature request! I think I'll hold off on adding this to the API/UI for now unless someone else wants to work on it

**Comment by giddel** [comment]
Export from v0.13 with Sqlite and import into v0.16 with Mysql worked! :-)
