### ISSUE TITLE
v1.1.0 docker image not available

### ISSUE THREAD

**Issue by darwin67** [markphelps/flipt#380]
Hello,

Looks like v1.1.0 is out for a while now but the images are not available on docker hub.
Would you mind building it and making it available?

Thanks

**Comment by markphelps** [comment]
Sorry about that, I managed to screw up the release process

Just published to both [DockerHub](https://hub.docker.com/layers/markphelps/flipt/v1.1.0/images/sha256-b2dc8c95512fcd1c5d957b30c8243a344ab278f8e3675abac5aa085c69989b5c?context=explore) and [GitHub](https://github.com/users/markphelps/packages/container/package/flipt)

**Comment by darwin67** [comment]
thank you!
wasn't aware that github now has a registry offering. pretty cool!

**Comment by markphelps** [comment]
yeah, I actually work on that team. so if you have any feature requests/bugs let me know!
