### ISSUE TITLE
UI fails to render segments or flags

### ISSUE THREAD

**Issue by rio** [markphelps/flipt#391]
The UI stays empty when requesting either segments or flags. The request tab does show entries being returned from the api. This happens on both Firefox 85.0.1 and Chrome 88.0.4324.182.

**Version Info**
Version: 1.2.0
Commit: 049e6ab29d47b04992f3338de5da43993b4bfb65
Build Date: 2021-02-23T09:09:50Z
Go Version: go1.15.5

**To Reproduce**
`docker run -ti --rm -p 8080:8080 markphelps:v1.2.0`

1. Open your browser to localhost:8080
2. Create a new flag
3. Click the on flags button in the top
4. Verify that the view stays empty
5. Open the network tab
6. Reload the page
7. Click on the flags request and open the response tab
8. Verify that the created flag is returned from the api 

**Expected behavior**
The views should render the data returned from the api.

**Screenshots**
![Screenshot from 2021-02-23 10-14-29](https://user-images.githubusercontent.com/883894/108822909-0b60dc80-75c0-11eb-836c-06e29f71f50a.png)

**Comment by markphelps** [comment]
@rio try `0.0.0.0:8080` there is a current issue with binding to localhost: https://github.com/markphelps/flipt/pull/388#issuecomment-782121157

**Comment by rio** [comment]
Thanks, I'll keep an eye on it!

**Comment by markphelps** [comment]
Update: I have a fix for this in #396. Once the tests run/pass I'll release v1.2.1

**Comment by rio** [comment]
Great! Can confirm this works. Thanks!
