### ISSUE TITLE
Segment search in match rule doesn't work

### ISSUE THREAD

**Issue by hagaishapira** [markphelps/flipt#462]
**Describe the bug**
When setting up a new rule and looking for a segment to match typing anything doesn't seem to search or offer appropriate segments to match.

**Version Info**
v1.2.1

**To Reproduce**
1. Create several segments
2. Create a new flag
3. Try to add a new rule to the flag. Typing in a portion of an existing segment name doesn't lead to showing only appropriate results.

**Expected behavior**
I expect that only appropriate segments that matched my typed input will show up in the dropdown list.

**Screenshots**
![image](https://user-images.githubusercontent.com/29172759/120651355-5c1d8680-c487-11eb-9bed-c0ef61a45d4b.png)
See how while I typed "hagai" I see the same results I've seen before typing anything.

**Additional context**

**Comment by markphelps** [comment]
Thanks for the bug report @hagaishapira ! I can confirm this same behavior. I will look into trying to fix this, likely an issue with the javascript library i'm using (buefy) to render this search

![Screen Shot 2021-06-04 at 11 23 16 AM](https://user-images.githubusercontent.com/209477/120825494-71e28880-c527-11eb-9c1b-7ae6252639af.png)

**Comment by markphelps** [comment]
@hagaishapira just fixed this in #475 and released a new version `1.3.0`. please give it a try! and thanks again for the bug report

**Comment by hagaishapira** [comment]
Thanks Mark, we will! Appreciate your hard work.

**Comment by hagaishapira** [comment]
@markphelps works great! This is has been a major pain point for the team for weeks now, we are all rejoiced.
