### ISSUE TITLE
Batch evaluation

### ISSUE THREAD

**Issue by andreyvital** [markphelps/flipt#61]
Maybe not a top priority right now...but do you think there's a way to batch-evaluate a set of flags?

I plan to use the REST API instead of grpc—so like, it'd be nice if I could send a single request with a set of flags to be evaluated instead of 1 request per flag. Just to avoid all the roundtrips.

Thoughts?

**Comment by markphelps** [comment]
Great idea. How would you expect the request body to look?

Something like this, where you evaluate multiple flags but with the same entity_id and context?:

```json
{
"request_id": "string",
"flag_keys": ["string", "string"],
"entity_id": "string",
"context": {
  "property1": "string",
  "property2": "string"
  }
}
```

Or, would you want to have different context/entity_ids for each flag, something like this:

```json
{
"request_id": "string",
"evaluations": [
  {
    "flag_key": "string",
    "entity_id": "string",
    "context": {
    "property1": "string",
    "property2": "string"
    }
  },
  {
    "flag_key": "string",
    "entity_id": "string",
    "context": {
    "property1": "string",
    "property2": "string"
    }
  },
  ]
}
```

**Comment by andreyvital** [comment]
Hmm...good question, the way I see it is that in the 1st case, who's consuming the API would have to guarantee that the context is appropriate to validate against all constraints in all the flags requested.

Case N2 we'd repeat the context which might increase the request payload... what about allowing both scenarios? one network-friendly and another more "flexible"?

```JSON
{
  "requestId": "1234",
  "entityId": "127.0.0.1",
  "globalContext": {
    "country": "UK",
    "property": "value"
  },
  "evaluations": [{
    "flagKey": "foo",
  }, {
    "flagKey": "bar",
    "context": {
      "country": "US"
    }
  }]
}
```

So the developer would consider `globalContext` for common things across all the flags whereas individual flags' context would be merged with `globalContext`, but notice, the override priority would come from the individual context

**Comment by sagikazarmark** [comment]
Is this actually done or just got closed due to inactivity?

I would also be interested in an evaluateAll  request, since a batch can grow pretty large. That would help integrate flipt into existing solutions.

**Comment by markphelps** [comment]
@sagikazarmark yeah it was closed due to inactivity. I'll reopen it if its a feature you'd like to see added.

Question about `evaluateAll`, in what order would it evaluate all the flags? By createdAt? Or would this be configurable per request

**Comment by sagikazarmark** [comment]
Hm, I'm not really interested in the order, I just need a list of the flags evaluated for a certain user.

**Comment by markphelps** [comment]
Good point, I guess the order wouldnt matter if the response returned `match=true/false` for each flag, not just the first one that matches.

**Comment by andreyvital** [comment]
@markphelps actually that's what needs to happen. It's just to avoid multiple HTTP roundtrips for each flag you know?
