### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by markphelps** [markphelps/flipt#8]
Would like a better logo and favicon but I'm not good at design ☹️ 

Something that represents feature flagging? flags? toggles?

**Comment by mirzazulfan** [comment]
Hi @markphelps What about this ? If you need to change please let me know.
![flipt](https://user-images.githubusercontent.com/36124339/53856967-025b5700-4007-11e9-9310-abdf020c06b2.png)

**Comment by markphelps** [comment]
@mirzazulfan I love it! Thank you soo much!

One suggestion I have is what about simplifying the bottom arm of the `f`, perhaps something like:

![flipt](https://user-images.githubusercontent.com/209477/53884340-640cc880-3fe9-11e9-91e2-d807faf0a322.png)

Forgive my horrible edit. Maybe also moving the bottom arm of the `f` up a bit? I couldnt manage to do that in Sketch (still learning). 

What are your thoughts?

**Comment by mirzazulfan** [comment]
Thanks for your response, im glad you liked it. Before I edit it, I will research it on the internet so that it is not the same as other people's designs. Best regard.

**Comment by markphelps** [comment]
Totally. Makes sense. Don't want it to look too similar to the Facebook f for sure haha.

One final set of ideas I had around the `F`, which are closer to your original designs I think are something like these maybe?

![img_0803](https://user-images.githubusercontent.com/209477/53888450-8ce58b80-3ff2-11e9-9f1f-297b0e34a643.jpg)

**Comment by mirzazulfan** [comment]
Hi @markphelps sorry for late reply, I was busy in the last week. How anout this?
![fff](https://user-images.githubusercontent.com/36124339/54523791-ed85a880-49a2-11e9-9bad-904fd98930ea.png)

**Comment by markphelps** [comment]
Hey @mirzazulfan no problem! I was also busy last week.

I like the second one a lot! Would it be possible to have that one along side the text 'flipt' like you did in your first post? Also with the different color backgrounds like you did previously?

Would you mind providing the sketch files or originals as well?

I was going to credit you in the README and documentation for coming up with the logo, does that work for you?

Thanks again!

**Comment by mirzazulfan** [comment]
@markphelps You can download all files [here](https://drive.google.com/drive/folders/14evg5EhPnFNmKnbdsBGdqvFQ-zZMHkjg) and pr #34
If you need anything change in the future don't hesitate to cantact me.
Best Regard.
