### ISSUE TITLE
Variants keys should be unique per flag, not globally

### ISSUE THREAD

**Issue by twgraham** [markphelps/flipt#87]
When trying to create a variant for a flag where the key is **default**, I'm getting an error suggesting that the key needs to be unique, despite the no existing variants for the flag. I do have a variant with the key **default** on another flag though.

I would expect that the keys for variants should be unique per flag rather than globally, since there is no way that these variants can be used across flags.

**Comment by markphelps** [comment]
Great point and thank you for the issue! Will work on this ASAP.

**Comment by markphelps** [comment]
@twgraham this has been merged, but am planning to make some changes on how migrations are run to make them safer before cutting a new release. should have that done and a new release cut by this weekend

**Comment by twgraham** [comment]
Woohoo! Thanks @markphelps 👍
