### ISSUE TITLE
Migrations not included in build

### ISSUE THREAD

**Issue by johnnynotsolucky** [markphelps/flipt#97]
Version 0.6.0
Binary installed to ~/flipt

Default configuration with exception of the sqlite3 db file located in ~/flipt, and migrations pointing to ~/flipt/config/migrations/sqlite3

Running `./flipt` results in error that ~/flipt/config/migrations/sqlite3 file does not exist.

Copying migrations from this repo into the migrations folder resolves the issue.

The last build to include migrations was 0.4.2.

**Comment by markphelps** [comment]
Oops. Thanks for finding that @johnnynotsolucky. I just released [v0.6.1](https://github.com/markphelps/flipt/releases/tag/v0.6.1) that should fix this issue.

Thanks again!
